// Generated
// by 
// from 
// at 24-10-2023 15:33:00

using System.Collections;
using System.Collections.Specialized;

namespace Eiscp.Core
{
	public static partial class EiscpCommands
	{
		public static readonly Dictionary<string, Dictionary<string, string>> CommandMappings = new Dictionary<string, Dictionary<string, string>>() {
			{ "main", new Dictionary<string, string>() {
				{ "system-power", "PWR" },
				{ "power", "PWR" },
				{ "audio-muting", "AMT" },
				{ "audio-muting-by-channel", "CMT" },
				{ "speaker-a", "SPA" },
				{ "speaker-b", "SPB" },
				{ "speaker-layout", "SPL" },
				{ "master-volume", "MVL" },
				{ "volume", "MVL" },
				{ "tone-front", "TFR" },
				{ "tone-front-wide", "TFW" },
				{ "tone-front-high", "TFH" },
				{ "tone-center", "TCT" },
				{ "tone-surround", "TSR" },
				{ "tone-surround-back", "TSB" },
				{ "tone-subwoofer", "TSW" },
				{ "phase-matching-bass", "PMB" },
				{ "sleep-set", "SLP" },
				{ "speaker-level-calibration", "SLC" },
				{ "subwoofer-temporary-level", "SWL" },
				{ "subwoofer-2-temporary-level", "SW2" },
				{ "center-temporary-level", "CTL" },
				{ "temporary-channel-level", "TCL" },
				{ "display-mode", "DIF" },
				{ "dimmer-level", "DIM" },
				{ "setup", "OSD" },
				{ "memory-setup", "MEM" },
				{ "reset", "RST" },
				{ "audio-information", "IFA" },
				{ "video-information", "IFV" },
				{ "fl-display-information", "FLD" },
				{ "input-selector", "SLI" },
				{ "source", "SLI" },
				{ "recout-selector", "SLR" },
				{ "audio-selector", "SLA" },
				{ "12v-trigger-a", "TGA" },
				{ "12v-trigger-b", "TGB" },
				{ "12v-trigger-c", "TGC" },
				{ "video-output-selector", "VOS" },
				{ "hdmi-output-selector", "HDO" },
				{ "hdmi-audio-out", "HAO" },
				{ "hdmi-audio-out-sub", "HAS" },
				{ "hdmi-cec", "CEC" },
				{ "hdmi-cec-control-monitor", "CCM" },
				{ "monitor-out-resolution", "RES" },
				{ "super-resolution", "SPR" },
				{ "hdmi-out-information", "HOI" },
				{ "isf-mode", "ISF" },
				{ "video-wide-mode", "VWM" },
				{ "video-picture-mode", "VPM" },
				{ "listening-mode", "LMD" },
				{ "direct", "DIR" },
				{ "late-night", "LTN" },
				{ "cinema-filter", "RAS" },
				{ "audyssey-2eq-multeq-multeq-xt", "ADY" },
				{ "audyssey-dynamic-eq", "ADQ" },
				{ "audyssey-dynamic-volume", "ADV" },
				{ "dolby-volume", "DVL" },
				{ "accueq", "AEQ" },
				{ "mcacc-eq", "MCM" },
				{ "equalizer-select", "EQS" },
				{ "eq-for-standing-wave-standing-wave", "STW" },
				{ "phase-control", "PCT" },
				{ "phase-control-plus", "PCP" },
				{ "lfe-level-lfe-mute-level", "LFE" },
				{ "all-channel-eq-for-temporary-value", "ACE" },
				{ "mcacc-calibration", "MCC" },
				{ "fullband-mcacc-calibration", "MFB" },
				{ "music-optimizer-sound-retriever", "MOT" },
				{ "a-v-sync", "AVS" },
				{ "audio-scalar", "ASC" },
				{ "upsampling", "UPS" },
				{ "hi-bit", "HBT" },
				{ "digital-filter", "DGF" },
				{ "lock-range-adjust", "LRA" },
				{ "p-bass", "PBS" },
				{ "s-bass", "SBS" },
				{ "screen-centered-dialog-dialog-enahncement", "SCD" },
				{ "center-spread-for-dolby-surround", "CTS" },
				{ "panorama-for-plii-music", "PNR" },
				{ "dimension-for-plii-music", "DMS" },
				{ "center-width-for-plii-music", "CTW" },
				{ "center-image-for-neo-6-music", "CTI" },
				{ "dialog-control", "DLC" },
				{ "dialog-control-enabled", "DCE" },
				{ "speaker-information", "SPI" },
				{ "speaker-distance", "SPD" },
				{ "input-channel-multiplex-dual-mono", "DMN" },
				{ "loudness-management", "LDM" },
				{ "intellivolume-input-volume-absorber", "ITV" },
				{ "input-selector-rename-input-function-rename", "IRN" },
				{ "pcm-fixed-mode-fixed-pcm-mode", "FXP" },
				{ "hdmi-standby-through", "HST" },
				{ "pqls", "PQL" },
				{ "audio-return-channel", "ARC" },
				{ "lip-sync-auto-delay", "LPS" },
				{ "auto-power-down", "APD" },
				{ "pre-amp-mode-amp-mode", "PAM" },
				{ "for-smart-grid", "ECO" },
				{ "firmware-version", "FWV" },
				{ "update", "UPD" },
				{ "popup-message", "POP" },
				{ "temperature-data", "TPD" },
				{ "tuning", "TUN" },
				{ "preset", "PRS" },
				{ "preset-memory", "PRM" },
				{ "rds-information", "RDS" },
				{ "pty-scan", "PTS" },
				{ "tp-scan", "TPS" },
				{ "xm-channel-name-info", "XCN" },
				{ "xm-artist-name-info", "XAT" },
				{ "xm-title-info", "XTI" },
				{ "xm-channel-number", "XCH" },
				{ "xm-category", "XCT" },
				{ "sirius-channel-name-info", "SCN" },
				{ "sirius-artist-name-info", "SAT" },
				{ "sirius-title-info", "STI" },
				{ "sirius-channel-number", "SCH" },
				{ "sirius-category", "SCT" },
				{ "sirius-parental-lock", "SLK" },
				{ "hd-radio-artist-name-info", "HAT" },
				{ "hd-radio-channel-name-info", "HCN" },
				{ "hd-radio-title-info", "HTI" },
				{ "hd-radio-detail-info", "HDS" },
				{ "hd-radio-channel-program", "HPR" },
				{ "hd-radio-blend-mode", "HBL" },
				{ "hd-radio-tuner-status", "HTS" },
				{ "battery-charge-status", "BCS" },
				{ "cd-player", "CCD" },
				{ "cd-play-status", "CST" },
				{ "current-disc-status-notice", "DST" },
				{ "current-folder-status-no", "CFS" },
				{ "cd-time-info", "CTM" },
				{ "set-cd-elapsed-time", "SCE" },
				{ "dab-station-name", "DSN" },
				{ "ctv", "CTV" }
		}
			},
			{ "zone2", new Dictionary<string, string>() {
				{ "power", "ZPW" },
				{ "zone-2-a", "ZPA" },
				{ "zone-2-b", "ZPB" },
				{ "muting", "ZMT" },
				{ "volume", "ZVL" },
				{ "tone", "ZTN" },
				{ "balance", "ZBL" },
				{ "selector", "SLZ" },
				{ "tuning", "TUZ" },
				{ "preset", "PRZ" },
				{ "net-tune-network", "NTZ" },
				{ "internet-radio-preset", "NPZ" },
				{ "listening-mode", "LMZ" },
				{ "late-night", "LTZ" },
				{ "re-eq-academy-filter", "RAZ" }
		}
			},
			{ "zone3", new Dictionary<string, string>() {
				{ "power", "PW3" },
				{ "muting", "MT3" },
				{ "volume", "VL3" },
				{ "tone", "TN3" },
				{ "balance", "BL3" },
				{ "selector", "SL3" },
				{ "tuning", "TU3" },
				{ "preset", "PR3" },
				{ "net-tune-network", "NT3" },
				{ "internet-radio-preset", "NP3" }
		}
			},
			{ "zone4", new Dictionary<string, string>() {
				{ "power", "PW4" },
				{ "muting", "MT4" },
				{ "volume", "VL4" },
				{ "selector", "SL4" },
				{ "tuning", "TU4" },
				{ "preset", "PR4" },
				{ "net-tune-network", "NT4" },
				{ "internet-radio-preset", "NP4" }
		}
			},
			{ "dock", new Dictionary<string, string>() {
				{ "network-usb", "NTC" },
				{ "bluetooth-setting", "NBS" },
				{ "bluetooth-internal", "NBT" },
				{ "net-usb-artist-name-info", "NAT" },
				{ "net-usb-album-name-info", "NAL" },
				{ "net-usb-title-name", "NTI" },
				{ "net-usb-time-info", "NTM" },
				{ "net-usb-track-info", "NTR" },
				{ "net-usb-play-status", "NST" },
				{ "net-usb-menu-status", "NMS" },
				{ "net-usb-time-seek", "NTS" },
				{ "internet-radio-preset", "NPR" },
				{ "net-connection-usb-device-status", "NDS" },
				{ "net-usb-list-info", "NLU" },
				{ "net-usb-jacket-art", "NJA" },
				{ "net-service", "NSV" },
				{ "net-keyboard", "NKY" },
				{ "net-popup-message", "NPU" },
				{ "net-usb-list-title-info", "NLT" },
				{ "ipod-mode-change", "NMD" },
				{ "network-standby-settings", "NSB" },
				{ "receiver-information", "NRI" },
				{ "net-usb-playback-view-button", "NPB" },
				{ "net-usb-add-favorite-list-in-list-view", "NAF" },
				{ "net-usb-remove-favorite-list", "NRF" },
				{ "net-usb-music-server-dlna-search-list", "NSD" },
				{ "airplay-artist-name-info", "AAT" },
				{ "airplay-album-name-info", "AAL" },
				{ "airplay-title-name", "ATI" },
				{ "airplay-time-info", "ATM" },
				{ "airplay-play-status", "AST" }
		}
			}
		};
	}
}
